name: 'build app'
on:
  pull-requests:
    branches:
      - master
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: 'clone repository'
        uses: actions/checkout@v3
      - name: 'setup node js'
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: 'install dependencies'
        run: npm install
      - name: 'build app'
        run: npm run build
