name: 'eslint'
on:
  pull_request:
    branches:
      - master
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: 'clone repository'
        uses: actions/checkout@v3
      - name: 'setup node js'
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: 'install dependencies'
        run: npm install
      - name: 'prettier format'
        run: npm run prettier
      - name: 'eslint check'
        run: npx eslint --max-warnings 0 ./src
