name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3
      - name: install dependents
        run: npm install
      - name: test run
        run: npm run test
      - name: eslint
        run: npm run lint
      - name: build run
        run: npm run build
      - name: deploy to firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_APP_9D757 }}'
          channelId: live
          projectId: test-app-9d757
